import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { RouterModule } from '@angular/router';
import { producto } from '../../model/producto.model';

@Component({
  selector: 'app-productos',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './productos.component.html',
  styleUrls: ['./productos.component.scss'],
})
export class ProductosComponent implements OnInit {

  productos: producto[] = [
    {
      id: 1,
      nombre: 'ADIDAS',
      descripcion: 'Zapatilla Forum Bold',
      color: 'Azul',
      precio: 179999,
      imagen: '/assets/zapatillas/formu1.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 2,
      nombre: 'ADIDAS',
      descripcion: 'Zapatilla Forum Bold',
      color: 'Blanco',
      precio: 179999,
      imagen: '/assets/zapatillas/formu2.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 3,
      nombre: 'ADIDAS',
      descripcion: 'Zapatilla Forum Bold',
      precio: 179999,
      color: 'Naranja',
      imagen: '/assets/zapatillas/formu3.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 4,
      nombre: 'ADIDAS',
      descripcion: 'Zapatilla Forum Low CL',
      color: 'Negro',
      precio: 149999,
      imagen: '/assets/zapatillas/formu4.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 5,
      nombre: 'ADIDAS',
      descripcion: 'Zapatilla Forum Bold',
      color: 'Verde',
      precio: 179999,
      imagen: '/assets/zapatillas/formu5.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 1,
      nombre: 'ADIDAS',
      descripcion: 'Zapatillas Campus 00s',
      color: 'Verde',
      precio: 169999,
      imagen: '/assets/zapatillas/campus1.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 2,
      nombre: 'ADIDAS',
      descripcion: 'Zapatillas Campus 00s',
      color: 'Negro',
      precio: 169999,
      imagen: '/assets/zapatillas/campus2.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 3,
      nombre: 'ADIDAS',
      descripcion: 'Zapatillas Campus 00s',
      precio: 179999,
      color: 'Rosa',
      imagen: '/assets/zapatillas/campus5.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 4,
      nombre: 'ADIDAS',
      descripcion: 'Zapatillas Campus 00s',
      color: 'Gris',
      precio: 169999,
      imagen: '/assets/zapatillas/campus3.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 5,
      nombre: 'ADIDAS',
      descripcion: 'Zapatillas Campus 00s',
      color: 'Rojo',
      precio: 169999,
      imagen: '/assets/zapatillas/campus4.avif',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 1,
      nombre: 'PUMA',
      descripcion: 'Zapatillas Suede XL Glam Athletics para mujer',
      color: 'Gris',
      precio: 20000,
      imagen: '/assets/zapatillas/glam1.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 2,
      nombre: 'PUMA',
      descripcion: 'Zapatillas Suede XL',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/suede1.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 3,
      nombre: 'PUMA',
      descripcion: 'Zapatillas Suede XL',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/suede2.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 4,
      nombre: 'PUMA',
      descripcion: 'Zapatillas Suede XL',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/suede3.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 5,
      nombre: 'PUMA',
      descripcion: 'Zapatilla Air Jordan 1 Low',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/suede4.png',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 1,
      nombre: 'PUMA',
      descripcion: 'Zapatillas Carina Street Lux para mujer',
      color: 'Gris',
      precio: 20000,
      imagen: '/assets/zapatillas/lux1.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 2,
      nombre: 'PUMA',
      descripcion: 'Zapatillas Carina Street Lux para mujer',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/lux2.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 3,
      nombre: 'PUMA',
      descripcion: 'Zapatillas CA Pro Classic II',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/pro1.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 4,
      nombre: 'PUMA',
      descripcion: 'Zapatillas CA Pro Classic II',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/pro2.png',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 5,
      nombre: 'PUMA',
      descripcion: 'Zapatillas CA Pro Classic II',
      color: 'Celeste',
      precio: 20000,
      imagen: '/assets/zapatillas/pro3.png',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 1,
      nombre: 'NIKE',
      descripcion: 'Zapatillas Air Force 1 07 ',
      color: 'Negro',
      precio: 199999,
      imagen: '/assets/zapatillas/air1.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 2,
      nombre: 'NIKE',
      descripcion: 'Zapatillas Air Force 1 07',
      color: 'Blanco',
      precio: 199999,
      imagen: '/assets/zapatillas/air2.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 3,
      nombre: 'NIKE',
      descripcion: 'Zapatillas Air Force 1 07',
      precio: 199999,
      color: 'Rosa',
      imagen: '/assets/zapatillas/air3.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 4,
      nombre: 'NIKE',
      descripcion: 'Zapatillas Air Force 1 07',
      color: 'Gris',
      precio: 199999,
      imagen: '/assets/zapatillas/air4.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 5,
      nombre: 'NIKE',
      descripcion: 'Zapatillas Air Force 1 07',
      color: 'Celeste',
      precio: 199999,
      imagen: '/assets/zapatillas/air5.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 1,
      nombre: 'NIKE',
      descripcion: 'Zapatilla Air Jordan 1 Low',
      color: 'Azul',
      precio: 199999,
      imagen: '/assets/zapatillas/jordan1.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 2,
      nombre: 'NIKE',
      descripcion: 'Zapatilla Air Jordan 1 Low',
      color: 'Blanco',
      precio: 199999,
      imagen: '/assets/zapatillas/jordan2.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 3,
      nombre: 'NIKE',
      descripcion: 'Zapatilla Air Jordan 1 Low',
      precio: 199999,
      color: 'Rosa',
      imagen: '/assets/zapatillas/jordan3.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 4,
      nombre: 'NIKE',
      descripcion: 'Zapatilla Air Jordan 1 Low',
      color: 'Negro',
      precio: 199999,
      imagen: '/assets/zapatillas/jordan4.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 5,
      nombre: 'NIKE',
      descripcion: 'Zapatilla Air Jordan 1 Low',
      color: 'Celeste',
      precio: 199999,
      imagen: '/assets/zapatillas/jordan5.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 1,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 480',
      color: 'Negro',
      precio: 119999,
      imagen: '/assets/zapatillas/480-1.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 2,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 480',
      color: 'Violetta',
      precio: 119999,
      imagen: '/assets/zapatillas/480-2.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 3,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 480',
      precio: 119999,
      color: 'Beigh',
      imagen: '/assets/zapatillas/480-3.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 4,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 480',
      color: 'Beigh-Verde',
      precio: 119999,
      imagen: '/assets/zapatillas/480-4.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 5,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 480',
      color: 'Blanco-Negro',
      precio: 119999,
      imagen: '/assets/zapatillas/480-5.webp',
      disponible: true,
      categoria: "",
      marca: "",
    }, {
      id: 1,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 550',
      color: 'Blanco-Negro',
      precio: 159999,
      imagen: '/assets/zapatillas/550-1.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 2,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 550',
      color: 'Blanco-Verde',
      precio: 159999,
      imagen: '/assets/zapatillas/550-2.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 3,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 550',
      precio: 159999,
      color: 'Blanco-Gris',
      imagen: '/assets/zapatillas/550-3.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 4,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 550',
      color: 'Blanco-Coral',
      precio: 159999,
      imagen: '/assets/zapatillas/550-4.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },
    {
      id: 5,
      nombre: 'NEW BALANCE',
      descripcion: 'Zapatilla 550',
      color: 'Blanco-Beigh',
      precio: 159999,
      imagen: '/assets/zapatillas/550-5.webp',
      disponible: true,
      categoria: "",
      marca: "",
    },

  ]

  constructor() { }
  /*
    AgregarFavoritos(producto: Producto) {
      this.favoritosService.agregarAfavoritos(producto)
      alert('Producto agregado a favoritos')
    }*/


  ngOnInit() { }

}
